### ISSUE TITLE
Reevaluate current exercises and bring them into a proper exercise tree 

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#199]
This is to prepare for the launch of v2.

It will propably not happen during this year, and there is currently a very basic tree set up to be able to participate in the beta.

I'd like to discuss how to organize the current exercises in the tree.

Especially I want to do the following:

* [ ] Decide upon which exercises should be core exercises
  * [ ] Order the core exercises
* [ ] Categorize exercises and label them correctly
* [ ] Make remaining exercises successors of core exercises, depending on their labels and difficulty

**Comment by sjwarner-bp** [comment]
My initial thought was that deciding which exercises are core or not will be easier if they are all categorised first, and then choose the easiest from each 'basic' category to be a core exercise.

I think that while many of the exercises are not implemented for this track, we could also probably still mirror many of the other tracks in their choice for core exercises, in order to remain consistent.

**Comment by NobbZ** [comment]
The checklist is not necessarily in order ;) Of course we can categorise and tag before deciding upon core exercises.

Simply taking core exercises from other languages, might work out, but it has to bone carefully.

Some concepts are just different to other languages. In erlang there is absolutely no mutability, so exercises that are in core just to introduce this feature won't make any sense in erlang. On the other hand side we do have pattern matching, a feature relatively unique to FP languages, this has to be introduced carefully, and I am even thinking about introducing an exercise tailored to it, which could be the second or third core. But I'm absolutely not sure about that right now...

**Comment by sjwarner-bp** [comment]
Yeah, I totally agree with you about certain aspects being language specific or FP specific. There are some concepts that apply well here that don't apply well on other tracks, and vice versa.

I feel that an exercise to those more niche aspects of FP or Erlang would be really good. While it is good to have core content, there is little point to having so many language tracks if we don't specialise!

**Comment by juhlig** [comment]
I have been doing some of the exercises on the Erlang track, and I find many of them lacking, mostly in the description, but also in consistency from exercise to exercise. I have to figure out a lot from the test cases instead, which is quite frustrating when it could have been just mentioned in the description instead.

The "Bob" exercise is one of the most lacking in that respect. For example, what exactly does "yelling" mean there? Turns out it is all-caps. A question seems to be clear, ends with a question mark. But a question in all caps is yelling. "actually don't say anything", what does that mean? It means a sentence of only spaces/tabs/linebreaks. All this has to be figured out of the 25 or so test cases.

Also, I think that exercises for any language should encourage patterns which are of importance to the understanding of that language. In the case of Erlang, specifically, this is the usage of pattern matching and recursion, but in the "Bob" exercise for example, many people just solve it by regular expressions. What did they learn in the line of Erlang through this example then?

Another thing is encouraging the let-it-crash mantra. In most cases, it would be proper to just provide no clauses for invalid input, or exit with reason badarg, but instead, many exercises encourage returning an error tuple, some even with a _string_ reason. And the description never tells you what is expected in case of invalid input, too. Dig it out of the tests.

The exercises never tell you what is actually expected in terms of return type. Sometimes it's ovious, but most of the time you have to dig it out of the test cases, where it may be hidden in some helper function (take the word count exercise, for example... the expected return type is dict, would you have guessed?)
This could be solved by adding `spec`s to the exercise skeletons. It will probably cause problems with old Erlang versions (because of namespaced types), but it would also help many people.

(On a side note, there should also be a way to inform reviewers of which Erlang version a solution was created. This way, the reviewers could give hints on things that have been deprecated or changed in a later version, for example the breaking change in `gen_statem`s init function somewhere between 17.0 and 17.3)

I'm actually in favor of TDD, but this is all unnecessarily frustrating, especially to newcomers to the language.

There are also exercises which are simply pointless. Two Fer, seriously, is this a joke? After doing Hamming distances and RNA transcriptions and fancy sounding things like that? If anything, this should be a follow up to Hello World.

To be fair, there are good exercises in the track as well. All the DNA-/RNA-related exercises are actually quite good and can be elegantly solved with Erlang. Also, the Robot Simulator is one good example.

To sum it all up, I think some kind of improved quality check for exercises would be a really good thing. I know that I can edit and redact the exercises myself, and I will. But I feel that quality control for exercises should really be improved for exercism, before accepting them.

**Comment by sjwarner-bp** [comment]
Hi @juhlig - @NobbZ runs most of this track, and I'm sure he will have some good input as he is far more experienced in erlang than I am.

I just wanted to mention the [problem-specifications](github.com/exercism/problem-specifications) repo as another good place to raise this kind of exercism-wide feedback. This is where most of the README comes from, and where decisions on a per-exercise basis are made.

Finally, I am not too sure when the READMEs were last regenerated / what version of tests the current implementation of `bob` here. I know that another test case was added not too long ago:
> He answers 'Calm down, I know what I'm doing!' if you yell a question at him.
which might have cleared up a bit of confusion.

**Comment by NobbZ** [comment]
>  I find many of [the exercises] lacking, mostly in the description

The READMEs description of each exercise is literally copied from its `description.md` available in the [problem-specifications](https://github.com/exercism/problem-specifications) repository.

And I do not plan on changing this for upstream exercises.

Also, a bit of this “vague” descriptions throughout the exercises is historically related to the fact that descriptions need to be language agnostic. Some other vague descriptions are just because a customer in real life isn't much clearer in formulating its intend. The iterative testing and failing then simulates the customer requesting changes after each iteration.

I know, this is not always ideal, but this is how exercism has been designed.

> In the case of Erlang, specifically, this is the usage of pattern matching and recursion,

which you will have plenty of options to, you can do that even in the bob exercise.

> but in the "Bob" exercise for example, many people just solve it by regular expressions

We can not do anything against that. If they want to use REs, let them. Honestly spoken, I used them as well in one or other language to solve bob.

I will never try to limit or restrict the modules available to the student. If its available in `stdlib` and `kernel`, he should just use it. If the student even wants to cheat himself and just uses a package from hex which already implements a bob-helper… Well, let him do this…

This is not ideal as well, especially since there is not much of reviewing going on in the erlang track, and I do not have enough time to spare to it.

I do hope though, that with the upcomming enforced mentoring the mentors will be able to push students into the right direction.

> Another thing is encouraging the let-it-crash mantra. In most cases, it would be proper to just provide no clauses for invalid input, or exit with reason badarg, but instead, many exercises encourage returning an error tuple, some even with a string reason. And the description never tells you what is expected in case of invalid input, too. Dig it out of the tests.

You can't teach philosophiy. Either people do understand, or they don't.

Aside of that, you are right, current behaviour of requiring error-tuples everywhere feels un-erlangish, but those are either very old before I even joined as maintainer, or because of the very stupid exercise generator.

I had not yet the time to revisit all of them to decide if actually an "maybe" is necessary here or if we just can crash.

Why those strings are not mentioned in the README is explained above.

> Sometimes it's ovious, but most of the time you have to dig it out of the test cases, where it may be hidden in some helper function (take the word count exercise, for example... the expected return type is dict, would you have guessed?)

No, I had not guessed, but also forgot that this was a thing back then. I had a hard time figuring it out as well. I think we can safely change this to a map nowadays… Feel free to open a PR.

> It will probably cause problems with old Erlang versions (because of namespaced types), but it would also help many people.

There are specs available for some exercise and not for others, I definitively need to revisit. I currently am not able to generate them for generated exercises…

Also namespaced types shouldn't be a problem anymore, since the latest officially supported OTP version supported by me is 18.x, which as far as I know already uses qualified types.

> (On a side note, there should also be a way to inform reviewers of which Erlang version a solution was created. This way, the reviewers could give hints on things that have been deprecated or changed in a later version, for example the breaking change in gen_statems init function somewhere between 17.0 and 17.3)

Yeah, would be nice, but not possible.

Therefore I do always assume the most current version at the time of the submission.

> There are also exercises which are simply pointless. Two Fer, seriously, is this a joke? After doing Hamming distances and RNA transcriptions and fancy sounding things like that? If anything, this should be a follow up to Hello World.

No. Hamming and transcription do some simple String/List processing, one does a map, the other a fold. Both have a single function with arity 1. Two-Fer though introduces the idea that functions with the same name and different arity are actually different functions. Since this is usually not possible in a language or only possible with default arguments or variadic argument lists or other uglyness, I like to keep this exercise where it is, and also I will definitively keep it as a core exercise for nextercism.

> But I feel that quality control for exercises should really be improved for exercism, before accepting them.

If you really feel like this, please refile this issue in one of the upstream trackers. I never have created an actual exercise (nor has any of my predecessor). We all just took from the pool of available ones and implemented them in erlang.

All in all, I thank you for your feedback. And I will definitfely consider some of your points.

**Comment by juhlig** [comment]
> The READMEs description of each exercise is literally copied from its
 > |description.md| available in the problem-specifications
 > <https://github.com/exercism/problem-specifications> repository.
 >
 > And I do not plan on changing this for upstream exercises.
 >
 > Also, a bit of this “vague” descriptions throughout the exercises is
 > historically related to the fact that descriptions need to be language
 > agnostic.

But it _is_ possible to tweak the READMEs for a language track, right? 
At least I saw some Erlang-specific amendmends somewhere, I think it was 
in the Robot Simulator exercise.

 > Some other vague descriptions are just because a customer in
 > real life isn't much clearer in formulating its intend. The iterative
 > testing and failing then simulates the customer requesting changes
 > after each iteration.

If that is the case, I wonder which audience exercism is actually 
targeting. I was assuming them to be largely on the beginner side of the 
spectrum (and most of the solutions I've seen so far show that this is 
the case). But I think for beginners who are struggling to become 
comfortable with a new language (and for most people new to Erlang, 
usually coming from imperative languages, literally everything 
Erlang-ish is new), this dig-it-out-of-the-tests thing is just 
frustrating. On the other hand, for any production-ready Erlang 
developer who would actually face customer specs and changes, the 
exercises are a mere pastime.

In other words, what is exercism trying to be, and who for?

Also, this kind of approach makes contributing a little difficult. For 
example, there was a bug in one of the exercise skeletons (don't 
remember which), a missing function or something. But is it actually a 
bug in the exercise? Or is finding that _part_ of the exercise?

 > which you will have plenty of options to, you can do that even in the
 > bob exercise.

Of course, and there were solutions who did it "right", but I think 
those were the experienced ones, while the ones who did it with REs were 
the beginners. It's not opportunities that are missing but directions.

 > We can not do anything against that. If they want to use REs, let
 > them.

I don't mean to do anything against it in terms of enforcing, but 
_encouraging_.

 > Honestly spoken, I used them as well in one or other language to solve
 > bob.

Heh, me too :) In fact, if it was any other language that I know, I 
would probably use REs without a second thought.

 > I will never try to limit or restrict the modules available to the
 > student. If its available in |stdlib| and |kernel|, he should just use
 > it. If the student even wants to cheat himself and just uses a package
 > from hex which already implements a bob-helper… Well, let him do this…

As I said, encourage, don't enforce.

 > This is not ideal as well, especially since there is not much of
 > reviewing going on in the erlang track, and I do not have enough time
 > to spare to it.

Well, I guess it gets tedious to politely discuss the same bad solutions 
over and over again. This is another reason why some pointers to what 
could be a good solution in the READMEs would be nice. Discussing the 
merits and pitfalls of good solutions is fun for the reviewers, so they 
will do it. Explaining why bad code is bad code is boring, so they won't 
bother.

 > I do hope though, that with the upcomming enforced mentoring the
 > mentors will be able to push students into the right direction.

That would be nice.

 > You can't teach philosophiy. Either people do understand, or they
 > don't.

It's not so much about _teaching_ philosophy, but exercises should guide 
on the path to understanding. As it is, however, the error-tuple stuff 
actually stands in the way of it.

 > Aside of that, you are right, current behaviour of requiring
 > error-tuples everywhere feels un-erlangish, but those are either very
 > old before I even joined as maintainer, or because of the very stupid
 > exercise generator.

Ok, understood ;)

 > No, I had not guessed, but also forgot that this was a thing back
 > then.
 > I had a hard time figuring it out as well. I think we can safely
 > change
 > this to a map nowadays… Feel free to open a PR.

Ok, but later. It's the week before deployment here at my place =^^=

 > Also namespaced types shouldn't be a problem anymore, since the latest
 > officially supported OTP version supported by me is 18.x, which as far
 > as I know already uses qualified types.

Since 17, iirc. Ok.

 > No. Hamming and transcription do some simple String/List processing,
 > one does a map, the other a fold. Both have a single function with
 > arity 1. Two-Fer though introduces the idea that functions with the
 > same name and different arity are actually different functions. Since
 > this is usually not possible in a language or only possible with
 > default arguments or variadic argument lists or other uglyness, I like
 > to keep this exercise where it is, and also I will definitively keep
 > it as a core exercise for nextercism.

This is the target audience thing again. Let's assume beginners. I guess 
most people new to Erlang learned it through "Learn You Some Erlang" (at 
least this is how it went for me. Don't know about others, the only 
other Erlang developers I ever saw in real life were at EFL). Taking 
this book as a sort of ad-hoc metric, the "arity thing" is mentioned 
first in chapter 2, and used seriously for the first time in chapter 5. 
Pattern matching and guards are in chapter 3. Recursion, crucial for 
most exercises, is chapter 5. The use of dicts and sets which is 
required (well, not strictly, you could do it with lists of course) for 
many exercises before Two-Fer, is chapter 9.
So, I feel that this particular exercise would be better placed at an 
earlier point in the track.

Now that I think about it, my misunderstanding of the point of the 
exercise shows that maybe there should be some mentioning of the 
objectives or intentions of some exercise?

Since this posting back and forth gets quite long-winded (which is my 
fault because I started with a long-winded post), maybe we should talk 
on IRC, if you're interested? We could even drop the english and speak 
german then, since it seems we're both from Germany ;)

Kind regards :)

**Comment by juhlig** [comment]
> The READMEs description of each exercise is literally copied from its
 > |description.md| available in the problem-specifications
 > <https://github.com/exercism/problem-specifications> repository.
 >
 > And I do not plan on changing this for upstream exercises.
 >
 > Also, a bit of this “vague” descriptions throughout the exercises is
 > historically related to the fact that descriptions need to be language
 > agnostic.

But it _is_ possible to tweak the READMEs for a language track, right? 
At least I saw some Erlang-specific amendmends somewhere, I think it was 
in the Robot Simulator exercise.

 > Some other vague descriptions are just because a customer in
 > real life isn't much clearer in formulating its intend. The iterative
 > testing and failing then simulates the customer requesting changes
 > after each iteration.

If that is the case, I wonder which audience exercism is actually 
targeting. I was assuming them to be largely on the beginner side of the 
spectrum (and most of the solutions I've seen so far show that this is 
the case). But I think for beginners who are struggling to become 
comfortable with a new language (and for most people new to Erlang, 
usually coming from imperative languages, literally everything 
Erlang-ish is new), this dig-it-out-of-the-tests thing is just 
frustrating. On the other hand, for any production-ready Erlang 
developer who would actually face customer specs and changes, the 
exercises are a mere pastime.

In other words, what is exercism trying to be, and who for?

Also, this kind of approach makes contributing a little difficult. For 
example, there was a bug in one of the exercise skeletons (don't 
remember which), a missing function or something. But is it actually a 
bug in the exercise? Or is finding that _part_ of the exercise?

 > which you will have plenty of options to, you can do that even in the
 > bob exercise.

Of course, and there were solutions who did it "right", but I think 
those were the experienced ones, while the ones who did it with REs were 
the beginners. It's not opportunities that are missing but directions.

 > We can not do anything against that. If they want to use REs, let
 > them.

I don't mean to do anything against it in terms of enforcing, but 
_encouraging_.

 > Honestly spoken, I used them as well in one or other language to solve
 > bob.

Heh, me too :) In fact, if it was any other language that I know, I 
would probably use REs without a second thought.

 > I will never try to limit or restrict the modules available to the
 > student. If its available in |stdlib| and |kernel|, he should just use
 > it. If the student even wants to cheat himself and just uses a package
 > from hex which already implements a bob-helper… Well, let him do this…

As I said, encourage, don't enforce.

 > This is not ideal as well, especially since there is not much of
 > reviewing going on in the erlang track, and I do not have enough time
 > to spare to it.

Well, I guess it gets tedious to politely discuss the same bad solutions 
over and over again. This is another reason why some pointers to what 
could be a good solution in the READMEs would be nice. Discussing the 
merits and pitfalls of good solutions is fun for the reviewers, so they 
will do it. Explaining why bad code is bad code is boring, so they won't 
bother.

 > I do hope though, that with the upcomming enforced mentoring the
 > mentors will be able to push students into the right direction.

That would be nice.

 > You can't teach philosophiy. Either people do understand, or they
 > don't.

It's not so much about _teaching_ philosophy, but exercises should guide 
on the path to understanding. As it is, however, the error-tuple stuff 
actually stands in the way of it.

 > Aside of that, you are right, current behaviour of requiring
 > error-tuples everywhere feels un-erlangish, but those are either very
 > old before I even joined as maintainer, or because of the very stupid
 > exercise generator.

Ok, understood ;)

 > No, I had not guessed, but also forgot that this was a thing back
 > then.
 > I had a hard time figuring it out as well. I think we can safely
 > change
 > this to a map nowadays… Feel free to open a PR.

Ok, but later. It's the week before deployment here at my place =^^=

 > Also namespaced types shouldn't be a problem anymore, since the latest
 > officially supported OTP version supported by me is 18.x, which as far
 > as I know already uses qualified types.

Since 17, iirc. Ok.

 > No. Hamming and transcription do some simple String/List processing,
 > one does a map, the other a fold. Both have a single function with
 > arity 1. Two-Fer though introduces the idea that functions with the
 > same name and different arity are actually different functions. Since
 > this is usually not possible in a language or only possible with
 > default arguments or variadic argument lists or other uglyness, I like
 > to keep this exercise where it is, and also I will definitively keep
 > it as a core exercise for nextercism.

This is the target audience thing again. Let's assume beginners. I guess 
most people new to Erlang learned it through "Learn You Some Erlang" (at 
least this is how it went for me. Don't know about others, the only 
other Erlang developers I ever saw in real life were at EFL). Taking 
this book as a sort of ad-hoc metric, the "arity thing" is mentioned 
first in chapter 2, and used seriously for the first time in chapter 5. 
Pattern matching and guards are in chapter 3. Recursion, crucial for 
most exercises, is chapter 5. The use of dicts and sets which is 
required (well, not strictly, you could do it with lists of course) for 
many exercises before Two-Fer, is chapter 9.
So, I feel that this particular exercise would be better placed at an 
earlier point in the track.

Now that I think about it, my misunderstanding of the point of the 
exercise shows that maybe there should be some mentioning of the 
objectives or intentions of some exercise?

Since this posting back and forth gets quite long-winded (which is my 
fault because I started with a long-winded post), maybe we should talk 
on IRC, if you're interested? We could even drop the english and speak 
german then, since it seems we're both from Germany ;)

Kind regards :)

**Comment by sjwarner-bp** [comment]
Not to jump into your conversation, and I am sure @NobbZ will reply in due course, but I have a quick answer to one of your questions:

> In other words, what is exercism trying to be, and who for?

Check out the [homepage](http://exercism.io/) - it shows you how exercism can be used from a couple of different points of view, including for newbies, experienced devs, and clean coders! :slightly_smiling_face:

**Comment by juhlig** [comment]
@sjwarner-bp Yes, I know. But the exercise levels of the tracks feel intermixed from exercise to exercise, and the pattern of the tests being the sometimes virtually only source of what is intended/required is spread across all the levels, which is part of the point I wanted to bring across in the paragraph before the one you cited.

**Comment by juhlig** [comment]
@sjwarner-bp By the way, I did just read the homepage text more carefully, and found that in the "Are you a code newbie?" article, it says that the exercises are _well-defined_, which is contradicted by the "descriptions are intentionally vague" statement. You couild argue that the exercises are well-defined _by the tests_, though...

**Comment by sjwarner-bp** [comment]
@juhlig I would imagine that is what the statement is referring to - the tests ultimately define expected behaviour throughout. Though if the statement is vague or confusing, it is could be worth rasing to fix :slightly_smiling_face:

**Comment by NobbZ** [comment]
I will close this for now.

Eventually we might do the track anatomy project which solely purpose it is to fix any issues with a tracks order of exercises.
